name: reddit_client
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  chewie: ^0.12.1+1
  dio: ^3.0.10
  draw: null
  equatable: null
  flutter_bloc: null
  flutter_link_preview: ^1.5.6
  flutter_markdown: ^0.5.2
  html_unescape: ^1.0.2
  http: null
  intl: ^0.16.1
  metadata_fetch: ^0.3.4
  rxdart: ^0.25.0
  timeago: ^2.0.29
  uni_links: ^0.4.0
  url_launcher: ^5.7.10
  uuid: null
  video_player: ^1.0.1
  video_provider: ^1.2.3+2
  youtube_player_flutter: ^7.0.0+7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_application_id: ^1.0.0
  flutter_launcher_icons: ^0.8.1
  mockito: null

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter_application_id:
  android:
    id: "com.yshean.amber"
    name: "Amber"
  ios:
    id: "com.yshean.amber"
    name: "Amber"
