name: reddit_client
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  draw: null
  equatable: null
  flutter_bloc: null
  http: null
  timeago: ^2.0.29
  uuid: null

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: null

flutter:
  uses-material-design: true
