name: reddit_client
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  chewie: ^0.12.1+1
  dio: ^3.0.10
  draw: null
  equatable: null
  flutter_bloc: null
  flutter_markdown: ^0.5.2
  html_unescape: ^1.0.2
  http: null
  metadata_fetch: ^0.3.4
  timeago: ^2.0.29
  url_launcher: ^5.7.10
  uuid: null
  video_player: ^1.0.1
  video_provider: ^1.2.3+2
  youtube_player_flutter: ^7.0.0+7

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: null

flutter:
  uses-material-design: true
